import { CssBaseline, ThemeProvider } from '@mui/material';
import themes from '@/themes';
import StoreProvider from './StoreProvider';
import GlobalLoader from '@/ui-components/Feedback/GlobalLoader';

import './globals.scss';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata = {
  title: 'NextJs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body>
          <ThemeProvider theme={themes}>
            <CssBaseline />
            <GlobalLoader />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
